// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/d765fdbf2517c151c69b9cb5afd86eff149cbce6/koa-static/koa-static.d.ts
declare module "koa-static" {

    import * as Koa from "koa";

    function serve(root: string, opts?: {
        
        /**
         * Default file name, defaults to 'index.html'
         */
        index?: boolean | string;
        
        /**
         * If true, serves after return next(),allowing any downstream middleware to respond first.
         */
        defer?: boolean;
        
        /**
         * Browser cache max-age in milliseconds. defaults to 0
         */
        maxage?: number;
        
        /**
         * Allow transfer of hidden files. defaults to false
         */
        hidden?: boolean;
        
        /**
         * Try to serve the gzipped version of a file automatically when gzip is supported by a client and if the requested file with .gz extension exists. defaults to true.
         */
        gzip?: boolean;
    }): { (ctx: Koa.Context, next?: () => any): any };
    namespace serve{}
    export = serve;
}
