/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['html[_ngcontent-%COMP%], body[_ngcontent-%COMP%]{\n    padding: 0;\n    margin: 0;\n    background: red;\n}\n.button[_ngcontent-%COMP%]{\n    background-color: red;\n}'];